# Generated by Django 4.2.13 on 2024-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tax_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
