# Generated by Django 4.2.13 on 2024-08-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_submerchantmodel_score'),
        ('users', '0004_user_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to='shops.shopmodel'),
        ),
    ]
