# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
