# Generated by Django 5.1.2 on 2024-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_birtday_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
