# Generated by Django 5.1.2 on 2024-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birtday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
