# Generated by Django 5.1.2 on 2025-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notificationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
