# Generated by Django 4.2.13 on 2024-05-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_attachmentmodel_is_deleted'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_image', to='attachment.attachmentmodel'),
        ),
    ]
