# Generated by Django 4.2.13 on 2024-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
