# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandmodel_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Marka Listesi'},
        ),
    ]
