# Generated by Django 4.2.13 on 2024-06-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_submerchantmodel_score'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs_shop', to='shops.shopmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specvaluemodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_value_shop', to='shops.shopmodel'),
            preserve_default=False,
        ),
    ]
