# Generated by Django 4.2.13 on 2024-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_specsmodel_shop_specvaluemodel_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specsmodel',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, related_name='specs_value', to='specs.specvaluemodel'),
        ),
    ]
