# Generated by Django 4.2.13 on 2024-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_alter_specsmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specsmodel',
            name='value',
            field=models.ManyToManyField(blank=True, related_name='specs_value', to='specs.specvaluemodel'),
        ),
    ]
