# Generated by Django 5.1.2 on 2025-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_alter_specsmodel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specvaluemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
