# Generated by Django 5.1.2 on 2025-02-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_alter_htmlfieldmodel_text'),
        ('specs', '0005_specsmodel_is_active_specvaluemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='specvaluemodel',
            name='specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='specs.specsmodel'),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specs_shop', to='shops.shopmodel'),
        ),
        migrations.AlterField(
            model_name='specsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_value_shop', to='shops.shopmodel'),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='specvaluemodel',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
