# Generated by Django 4.1.13 on 2024-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdatamodels',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
