# Generated by Django 5.1.2 on 2025-02-13 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0050_alter_productmodel_spec_values'),
        ('shops', '0025_alter_htmlfieldmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopComparisonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_difference_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_cheaper', models.BooleanField(default=False)),
                ('price_history_data', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('competitor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_competitor_product', to='products.productmodel')),
                ('competitor_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_competitor_shop', to='shops.shopmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_product', to='products.productmodel')),
            ],
            options={
                'verbose_name_plural': 'Mağaza Karşılaştırmaları',
                'db_table': 'shop_comparisons',
                'ordering': ['id'],
            },
        ),
    ]
