# Generated by Django 5.1.2 on 2025-02-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopCompare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcomparisonmodel',
            name='price_history_data',
        ),
    ]
