# Generated by Django 4.2 on 2023-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsmodels',
            name='cdn_systems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettingsmodels',
            name='mail_systems',
            field=models.IntegerField(default=0),
        ),
    ]
