# Generated by Django 4.2.13 on 2024-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_sitesettingsmodels_cdn_systems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsmodels',
            name='bucket',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
