# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_sitesettingsmodels_bucket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettingsmodels',
            options={'ordering': ['id'], 'verbose_name_plural': 'Site Ayarları'},
        ),
    ]
