# Generated by Django 5.1.2 on 2025-02-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_category_alter_blogmodel_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
    ]
