# Generated by Django 5.1.2 on 2025-02-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0011_alter_attachmentmodel_original_file_url'),
        ('blog', '0004_remove_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.attachmentmodel'),
        ),
    ]
