# Generated by Django 5.1.2 on 2025-02-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
    ]
