# Generated by Django 4.2.13 on 2024-05-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categoriesmodel_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='is_active',
            new_name='is_status',
        ),
    ]
