# Generated by Django 4.2.13 on 2024-05-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_is_active_categoriesmodel_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
