# Generated by Django 4.2.13 on 2024-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0005_alter_categoriesmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories_brand', to='brands.brandmodel'),
        ),
    ]
