# Generated by Django 4.2.13 on 2024-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandmodel_is_main'),
        ('categories', '0006_categoriesmodel_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories_brand', to='brands.brandmodel'),
        ),
    ]
