# Generated by Django 4.2.13 on 2024-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_categoriesmodel_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='name',
            field=models.CharField(max_length=600),
        ),
    ]
