# Generated by Django 4.2.13 on 2024-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_categoriesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
