# Generated by Django 4.2.13 on 2024-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        ('categories', '0011_alter_categoriesmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='specs',
            field=models.ManyToManyField(blank=True, related_name='categories_specs', to='specs.specsmodel'),
        ),
    ]
