# Generated by Django 4.2.13 on 2024-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_categoriesmodel_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='product_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
