# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_categoriesmodel_product_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
