# Generated by Django 4.2.13 on 2024-08-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_alter_categoriesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
