# Generated by Django 4.2.13 on 2024-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_alter_categoriesmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='is_adult',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
