# Generated by Django 5.1.2 on 2025-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_categoriesmodel_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
