# Generated by Django 4.2.13 on 2024-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_submerchantmodel_shopmodel_sub_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='submerchantmodel',
            name='sync_service',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submerchantmodel',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
