# Generated by Django 4.2.13 on 2024-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_submerchantmodel_sync_service_submerchantmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='sync_service',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
