# Generated by Django 4.2.13 on 2024-05-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopmodel_sync_service_shopmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMlMapsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=400)),
                ('value', models.CharField(max_length=400)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopmodel')),
            ],
            options={
                'db_table': 'shop_xml_maps',
                'ordering': ['-id'],
            },
        ),
    ]
