# Generated by Django 4.2.13 on 2024-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_xmlmapsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='xml_map',
            field=models.ManyToManyField(blank=True, related_name='xml_map_shop', to='shops.xmlmapsmodel'),
        ),
    ]
