# Generated by Django 4.2.13 on 2024-06-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shopmodel_xml_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlmapsmodel',
            name='shop',
        ),
    ]
