# Generated by Django 4.2.13 on 2024-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_remove_xmlmapsmodel_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='submerchantmodel',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
