# Generated by Django 4.2.13 on 2024-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_submerchantmodel_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='cargo_barem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
