# Generated by Django 4.2.13 on 2024-08-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_attachmentmodel_is_deleted'),
        ('shops', '0009_shopmodel_cargo_barem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='tax_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_document_shop', to='attachment.attachmentmodel'),
        ),
    ]
