# Generated by Django 4.2.13 on 2024-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_shopmodel_tax_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='trendyol_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='trendyol_api_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='trendyol_shop_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
