# Generated by Django 4.2.13 on 2024-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_shopmodel_is_active_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='shop_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
