# Generated by Django 4.2.13 on 2024-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_shopmodel_shop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='web_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
