# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_shopmodel_web_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmodel',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Mağaza Listesi'},
        ),
        migrations.AlterModelOptions(
            name='xmlmapsmodel',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Eşleştirme Alanları'},
        ),
    ]
