# Generated by Django 5.1.2 on 2024-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brandmodel_options'),
        ('shops', '0017_submerchantmodel_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='brands',
            field=models.ManyToManyField(blank=True, null=True, to='brands.brandmodel'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
