# Generated by Django 5.1.2 on 2024-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brandmodel_options'),
        ('shops', '0018_shopmodel_brands_shopmodel_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='brands',
            field=models.ManyToManyField(blank=True, to='brands.brandmodel'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='shop_description',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
