# Generated by Django 5.1.2 on 2024-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_alter_submerchantmodel_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_class', models.CharField(blank=True, max_length=400, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=400, null=True)),
                ('tag_attr', models.CharField(blank=True, max_length=400, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(max_length=400)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'HTML Eşleştirme Alanları',
                'db_table': 'shop_html_maps',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='html_map',
            field=models.ManyToManyField(blank=True, related_name='html_map_shop', to='shops.htmlfieldmodel'),
        ),
    ]
