# Generated by Django 5.1.2 on 2024-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_htmlfieldmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlfieldmodel',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
