# Generated by Django 5.1.2 on 2024-11-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0023_htmlfieldmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlfieldmodel',
            name='tag_attr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
