# Generated by Django 5.1.2 on 2024-11-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0024_alter_htmlfieldmodel_tag_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlfieldmodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
