# Generated by Django 5.1.2 on 2025-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_alter_htmlfieldmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='ikas_api_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
