# Generated by Django 5.1.2 on 2025-02-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_shopmodel_ikas_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='ikas_image_bucket',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
