# Generated by Django 5.1.2 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_shopmodel_ikas_image_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
