# Generated by Django 5.1.2 on 2025-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0028_shopmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='is_browser',
            field=models.BooleanField(default=False),
        ),
    ]
