from django.core.management.base import BaseCommand

from shops.models import ShopModel, XMlMapsModel


class Command(BaseCommand):
    help = 'Seeds the database'

    def handle(self, *args, **kwargs):
        shop = ShopModel.objects.create(name='Trendyol', url='https://transport.productsup.io/8c47306d8cefa9dc0b55/channel'
                                                      '/601642/Fiyator.csv', sync_service=1)
        name = XMlMapsModel.objects.create(field_name='name', value='0')
        slug = XMlMapsModel.objects.create(field_name='slug', value='0')
        link = XMlMapsModel.objects.create(field_name='link', value='1')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='4')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='6')
        price = XMlMapsModel.objects.create(field_name='price', value='12')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='21')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='15')
        image = XMlMapsModel.objects.create(field_name='image', value='2')
        brand = XMlMapsModel.objects.create(field_name='brand', value='14')
        sub_merchant_id = XMlMapsModel.objects.create(field_name='sub_merchant_id', value='23')
        category = XMlMapsModel.objects.create(field_name='category', value='17')
        sku = XMlMapsModel.objects.create(field_name='sku', value='5')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='13')
        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(sub_merchant_id)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop = ShopModel.objects.create(name='Teknosa', url='https://transport.productsup.io/9453383eed0c8c84268d/channel'
                                                     '/157894/teknosa-pup-cimri.xml')
        name = XMlMapsModel.objects.create(field_name='name', value='itemTitle')
        slug = XMlMapsModel.objects.create(field_name='slug', value='itemTitle')
        link = XMlMapsModel.objects.create(field_name='link', value='itemUrl')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='merchantItemId')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='ean')
        price = XMlMapsModel.objects.create(field_name='price', value='priceEft')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shippingFee')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='merchantName')
        image = XMlMapsModel.objects.create(field_name='image', value='itemImageUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='brand')
        category = XMlMapsModel.objects.create(field_name='category', value='merchantItemCategoryName')
        sku = XMlMapsModel.objects.create(field_name='sku', value='-')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='http://www.cimri.com/schema/merchant/upload')
        item = XMlMapsModel.objects.create(field_name='item', value='MerchantItem')
        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)

        ShopModel.objects.create(name='PTT AVM', url='https://storage.crwizard.com/ptt/fiyator.xml')
        name = XMlMapsModel.objects.create(field_name='name', value='title')
        slug = XMlMapsModel.objects.create(field_name='slug', value='title')
        link = XMlMapsModel.objects.create(field_name='link', value='link')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='-')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='-')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='image_link')
        brand = XMlMapsModel.objects.create(field_name='brand', value='brand')
        category = XMlMapsModel.objects.create(field_name='category', value='product_type')
        sku = XMlMapsModel.objects.create(field_name='sku', value='-')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./channel/product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)

        shop = ShopModel.objects.create(name='ROBORGE', url='https://www.roborge.com/XMLExport'
                                                     '/352D63DD77314A22A4FBA2380E1FF363')

        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='-')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='DAVID WALKER', url='https://www.e-davidwalker.com/XMLExport'
                                                         '/27E36DA26B664EDF810DB1E42F14DF2B')

        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='-')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='ELEKTRIK SANAL MARKET',
                                 url='https://www.elektriksanalmarket.com/index.php?do=catalog/output'
                                     '&pCode=5886374648')

        name = XMlMapsModel.objects.create(field_name='name', value='title')
        slug = XMlMapsModel.objects.create(field_name='slug', value='title')
        link = XMlMapsModel.objects.create(field_name='link', value='link')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='-')
        price = XMlMapsModel.objects.create(field_name='price', value='g:price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='-')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='g:image_link')
        brand = XMlMapsModel.objects.create(field_name='brand', value='g:brand')
        category = XMlMapsModel.objects.create(field_name='category', value='g:product_type')
        sku = XMlMapsModel.objects.create(field_name='sku', value='-')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='g, http://base.google.com/ns/1.0')
        item = XMlMapsModel.objects.create(field_name='item', value='./channel/item')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='VIASPOR',
                                 url='https://viaspor.com/XMLExport/8CD653C79D084678BCF27C57B32907E2')
        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='DİP FİYAT',
                                 url='https://www.dipfiyata.net/XMLExport/2D76216C471B4361993CAECEC9AF0A61')

        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='EN UCUZ TESİSAT',
                                 url='https://www.enucuztesisat.com/XMLExport/A5A30348447942DC93C26E44CFDC5ECB')
        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='GALİPOĞLU',
                                 url='https://www.galipoglu.com/XMLExport/67BE4288A2DE4D4E9FDA7A8C6F10E520')
        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='GOLD MÜZİK',
                                 url='https://www.goldmuzikmarket.com/XMLExport/6C79960115CD4B9FA6322FA07B36B7FC')
        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
        shop = ShopModel.objects.create(name='ATC ORGANİK',
                                 url='https://www.atcorganik.com/XMLExport/BF1161980C264AFA97C76959A07700D0')
        name = XMlMapsModel.objects.create(field_name='name', value='name')
        slug = XMlMapsModel.objects.create(field_name='slug', value='name')
        link = XMlMapsModel.objects.create(field_name='link', value='url')
        model_code = XMlMapsModel.objects.create(field_name='model_code', value='-')
        barcode = XMlMapsModel.objects.create(field_name='barcode', value='barcode')
        price = XMlMapsModel.objects.create(field_name='price', value='price')
        cargo_price = XMlMapsModel.objects.create(field_name='cargo_price', value='shipPrice')
        sub_merchant_shop = XMlMapsModel.objects.create(field_name='sub_merchant_shop', value='-')
        image = XMlMapsModel.objects.create(field_name='image', value='imgUrl')
        brand = XMlMapsModel.objects.create(field_name='brand', value='productBrand')
        category = XMlMapsModel.objects.create(field_name='category', value='productCategory')
        sku = XMlMapsModel.objects.create(field_name='sku', value='sku')
        kdv = XMlMapsModel.objects.create(field_name='kdv', value='-')
        ns = XMlMapsModel.objects.create(field_name='ns', value='-')
        item = XMlMapsModel.objects.create(field_name='item', value='./product')

        shop.xml_map.add(name)
        shop.xml_map.add(slug)
        shop.xml_map.add(link)
        shop.xml_map.add(model_code)
        shop.xml_map.add(barcode)
        shop.xml_map.add(price)
        shop.xml_map.add(cargo_price)
        shop.xml_map.add(sub_merchant_shop)
        shop.xml_map.add(image)
        shop.xml_map.add(brand)
        shop.xml_map.add(category)
        shop.xml_map.add(sku)
        shop.xml_map.add(kdv)
        shop.xml_map.add(ns)
        shop.xml_map.add(item)
