# Generated by Django 4.2.13 on 2024-09-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksmodel',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Tasks'},
        ),
    ]
