# Generated by Django 4.2 on 2023-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('orjinal_file_url', models.CharField(max_length=500)),
                ('thumb_file_url', models.CharField(max_length=500)),
                ('orjinal_name', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['id'],
            },
        ),
    ]
