# Generated by Django 4.2.13 on 2024-05-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentmodel',
            old_name='orjinal_file_url',
            new_name='original_file_url',
        ),
        migrations.RenameField(
            model_name='attachmentmodel',
            old_name='orjinal_name',
            new_name='original_name',
        ),
    ]
