# Generated by Django 4.2.13 on 2024-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_rename_orjinal_file_url_attachmentmodel_original_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size_byte', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_meta_data',
                'ordering': ['id'],
            },
        ),
    ]
