# Generated by Django 4.2.13 on 2024-05-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_filemetadatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
