# Generated by Django 4.2.13 on 2024-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_attachmentmodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='original_file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentmodel',
            name='original_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
