# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0006_alter_attachmentmodel_original_file_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentmodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Resimler'},
        ),
    ]
