# Generated by Django 4.2.13 on 2024-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0007_alter_attachmentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadatamodel',
            name='file_name',
            field=models.CharField(max_length=500),
        ),
    ]
