# Generated by Django 4.2.13 on 2024-08-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0008_alter_filemetadatamodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadatamodel',
            name='file_hash',
            field=models.CharField(max_length=150),
        ),
    ]
