# Generated by Django 4.2.13 on 2024-08-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0009_alter_filemetadatamodel_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadatamodel',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
    ]
