# Generated by Django 4.2.13 on 2024-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0010_alter_filemetadatamodel_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmodel',
            name='original_file_url',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
