# Generated by Django 5.1.2 on 2024-10-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_alter_shopmodel_options_alter_xmlmapsmodel_options'),
        ('synchronize_error', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizeUrlsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synchronize_url_shop', to='shops.shopmodel')),
            ],
            options={
                'db_table': 'synchronize_url',
                'ordering': ['id'],
            },
        ),
    ]
