# Generated by Django 5.1.2 on 2024-11-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0002_synchronizeurlsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizeurlsmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_urls', to='synchronize_error.synchronizeurlsmodel'),
        ),
    ]
