# Generated by Django 5.1.2 on 2024-11-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0003_synchronizeurlsmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizeurlsmodel',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
