# Generated by Django 5.1.2 on 2024-11-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0004_synchronizeurlsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizeurlsmodel',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
