# Generated by Django 5.1.2 on 2024-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0005_synchronizeurlsmodel_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizeurlsmodel',
            name='url',
            field=models.TextField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
