# Generated by Django 5.1.2 on 2024-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0006_alter_synchronizeurlsmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizemodel',
            name='script_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
