# Generated by Django 5.1.2 on 2025-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_error', '0007_synchronizemodel_script_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizemodel',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synchronizemodel',
            name='try_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
