# Generated by Django 4.2.13 on 2024-05-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmodel',
            old_name='mailtype',
            new_name='mail_type',
        ),
    ]
