# Generated by Django 4.2.13 on 2024-05-11 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='stock_code',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cargo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
