# Generated by Django 4.2.13 on 2024-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='gtin_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
