# Generated by Django 4.2.13 on 2024-05-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_submerchantmodel_shopmodel_sub_merchant'),
        ('products', '0007_productmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sub_merchant_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_merchant_shop', to='shops.submerchantmodel'),
        ),
    ]
