# Generated by Django 4.2.13 on 2024-05-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_is_active_categoriesmodel_is_status'),
        ('products', '0008_productmodel_sub_merchant_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='categories.categoriesmodel'),
        ),
    ]
