# Generated by Django 4.2.13 on 2024-05-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_submerchantmodel_shopmodel_sub_merchant'),
        ('products', '0010_alter_productmodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_shop', to='shops.shopmodel')),
                ('sub_merchant_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_sub_merchant_shop', to='shops.submerchantmodel')),
            ],
            options={
                'db_table': 'products_prices',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price_history',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_product_history', to='products.productpricemodel'),
        ),
    ]
