# Generated by Django 4.2.13 on 2024-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productpricemodel_productmodel_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='model_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
