# Generated by Django 4.2.13 on 2024-05-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodel_model_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='model_kodu',
        ),
    ]
