# Generated by Django 4.2.13 on 2024-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productmodel_model_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
