# Generated by Django 4.2.13 on 2024-05-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productmodel_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-id']},
        ),
    ]
