# Generated by Django 4.2.13 on 2024-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='match',
            field=models.ManyToManyField(blank=True, related_name='product_match', to='products.productmodel'),
        ),
    ]
