# Generated by Django 4.2.13 on 2024-05-29 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_productmodel_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUserClickModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('browser', models.CharField(blank=True, max_length=1000, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_family', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_user_clicks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click', models.ManyToManyField(blank=True, null=True, to='products.productuserclickmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_product', to='products.productmodel')),
            ],
            options={
                'db_table': 'products_events',
                'ordering': ['id'],
            },
        ),
    ]
