# Generated by Django 4.2.13 on 2024-05-30 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productuserclickmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpricemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
