# Generated by Django 4.2.13 on 2024-05-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productpricemodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='products.productmodel')),
            ],
            options={
                'db_table': 'products_discount',
                'ordering': ['id'],
            },
        ),
    ]
