# Generated by Django 4.2.13 on 2024-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productdiscountmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteventmodel',
            name='click',
            field=models.ManyToManyField(blank=True, related_name='event_click', to='products.productuserclickmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price_history',
            field=models.ManyToManyField(blank=True, related_name='product_product_history', to='products.productpricemodel'),
        ),
    ]
