# Generated by Django 4.2.13 on 2024-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_producteventmodel_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
