# Generated by Django 4.2.13 on 2024-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        ('products', '0022_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='spec_values',
            field=models.ManyToManyField(blank=True, to='specs.specvaluemodel'),
        ),
    ]
