# Generated by Django 4.2.13 on 2024-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productmodel_spec_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='command_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
