# Generated by Django 4.2.13 on 2024-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productmodel_command_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
