# Generated by Django 4.2.13 on 2024-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productmodel_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='syncronize_status',
            field=models.BooleanField(default=False),
        ),
    ]
