# Generated by Django 4.2.13 on 2024-07-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productmodel_is_match_productmodel_syncronize_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
    ]
