# Generated by Django 4.2.13 on 2024-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productratemodel_productcommentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
