# Generated by Django 4.2.13 on 2024-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productlistuserview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='link',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
