# Generated by Django 4.2.13 on 2024-08-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_productmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
