# Generated by Django 4.2.13 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_productmodel_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteventmodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ürün Tıklamaları'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ürün Listesi'},
        ),
        migrations.AlterModelOptions(
            name='productuserclickmodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Kullanıcı Tıklamaları'},
        ),
    ]
