# Generated by Django 4.2.13 on 2024-08-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_productmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ürün Listesi'},
        ),
    ]
