# Generated by Django 4.2.13 on 2024-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
