# Generated by Django 4.2.13 on 2024-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_productmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='link',
            field=models.URLField(db_index=True, max_length=2000, unique=True),
        ),
    ]
