# Generated by Django 5.1.2 on 2024-11-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_productmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
