# Generated by Django 5.1.2 on 2024-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_productmodel_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
