# Generated by Django 5.1.2 on 2024-12-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_productmodel_is_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='is_lock',
        ),
    ]
