# Generated by Django 5.1.2 on 2025-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_remove_productmodel_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricealarmmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
