# Generated by Django 5.1.2 on 2025-01-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_productpricealarmmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricealarmmodel',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
