# Generated by Django 5.1.2 on 2025-01-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_productpricealarmmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricealarmmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
