# Generated by Django 5.1.2 on 2025-01-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_productpricealarmmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.productmodel'),
        ),
    ]
