# Generated by Django 5.1.2 on 2025-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_productmodel_final_score_productmodel_match_score_and_more'),
        ('specs', '0005_specsmodel_is_active_specvaluemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='specs',
            field=models.ManyToManyField(blank=True, related_name='product_specs', to='specs.specsmodel'),
        ),
    ]
