# Generated by Django 5.1.2 on 2025-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_productmodel_specs'),
        ('specs', '0006_specvaluemodel_specs_alter_specsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='spec_values',
            field=models.ManyToManyField(blank=True, related_name='product_spec_values', to='specs.specvaluemodel'),
        ),
    ]
