# Generated by Django 5.1.2 on 2025-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_productmodel_spec_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
